apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    env: prod
    app: nginx-web
spec:
  containers:
  - name: container-1
    image: nginx
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    env: hml
    app: nginx-web
spec:
  containers:
  - name: container-2
    image: nginx
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
    ports:
      - containerPort: 80


apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    env: dev
    app: nginx-web
spec:
  containers:
  - name: container-3
    image: nginx
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
    ports:
      - containerPort: 80