apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-homologacao
  namespace: homologacao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-homologacao
subjects:
  - kind: ServiceAccount
    name: sysadmin
    namespace: homologacao
  