apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  labels:
    name: pod-5
spec:
  containers:
  - name: pod-5
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "10m"
      requests:
        cpu: "10m"
    ports:
      - containerPort: 80