apiVersion:v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP  
    port: 80
    targetPort: 8080
    nodePort: 30000
