apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site1-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-site1-middleware@kubernetescrd
  labels:
    name: site1
spec:
  rules:
    - http:
      paths:
      - pathType: Prefix
        path: "/site1"
        backend:
          service: 
            name: site1-service
            port: 
              number: 80